name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Check for security vulnerabilities
      run: npm audit --production

    - name: Lint with ESLint
      run: npm run lint

    - name: Run tests
      run: npm run test:cov
      
# can then update coverage to codecov
